name = "pocketglow_async_basic"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = "An example that demonstrates async operations using a Recipe Finder"
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "adkelley", repo = "pocketglow" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
pocketglow = { git = "https://github.com/adkelley/pocketglow", ref = "main"}
task = { git = "https://github.com/adkelley/task", ref = "main"}
gleam_erlang = ">= 1.2.0 and < 2.0.0"
input = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
